# NO-OP placeholder that always passes for other paths
# This is here so that we're able to set the status check as required

name: E2E Windows Void
on:
  pull_request:
    paths-ignore:
      - 'yarn.lock'
      - '.github/workflows/verify_e2e-windows.yml'
      - 'packages/cli/**'
      - 'packages/e2e-test/**'
      - 'packages/create-app/**'

permissions:
  contents: read

jobs:
  noop:
    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    name: E2E Windows ${{ matrix.node-version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
        with:
          egress-policy: audit

      - run: echo NOOP
